from scale import Scales


class CannonR:

    def __init__(self):
        self.name = "CannonC"
        self.music = Scales(120)

    def generator(self):
        # ---------------- start ---------------------#
        # 1
        self.music.e5(4)
        self.music.d5(4)
        self.music.modify_time(8, 1)
        self.music.c4(4)
        self.music.g3(4)
        # 2
        self.music.c5(4)
        self.music.b4(4)
        self.music.modify_time(8, 1)
        self.music.a3(4)
        self.music.e3(4)
        # 3
        self.music.a4(4)
        self.music.g4(4)
        self.music.modify_time(8, 1)
        self.music.f3(4)
        self.music.a3(4)
        # 4
        self.music.a4(4)
        self.music.b4(4)
        self.music.modify_time(8, 1)
        self.music.f3(4)
        self.music.g3(4)
        # 5
        self.music.e6(4)
        self.music.modify_time(4, 1)
        self.music.g5(4)
        self.music.d6(4)
        self.music.modify_time(4, 1)
        self.music.g5(4)
        self.music.modify_time(8, 1)
        self.music.c4(4)
        self.music.g3(4)
        # 6
        self.music.c6(4)
        self.music.modify_time(4, 1)
        self.music.e5(4)
        self.music.b5(4)
        self.music.modify_time(4, 1)
        self.music.e5(4)
        self.music.modify_time(8, 1)
        self.music.a3(4)
        self.music.e3(4)
        # 7
        self.music.a5(4)
        self.music.modify_time(4, 1)
        self.music.c5(4)
        self.music.g5(4)
        self.music.modify_time(4, 1)
        self.music.c5(4)
        self.music.modify_time(8, 1)
        self.music.f3(4)
        self.music.c4(4)
        # 8
        self.music.a5(4)
        self.music.modify_time(4, 1)
        self.music.c5(4)
        self.music.b5(4)
        self.music.modify_time(4, 1)
        self.music.d5(4)
        self.music.modify_time(8, 1)
        self.music.f3(4)
        self.music.g3(4)
        # 9
        self.music.e6(4)
        self.music.modify_time(4, 1)
        self.music.g5(4)
        self.music.d6(2)
        self.music.modify_time(2, 1)
        self.music.g5(2)
        self.music.f5(2)
        self.music.modify_time(8, 1)
        self.music.c4(1)
        self.music.g4(1)
        self.music.c5(1)
        self.music.e5(1)
        self.music.b3(1)
        self.music.d4(1)
        self.music.g4(1)
        self.music.b4(1)
        # 10
        self.music.c6(4)
        self.music.b5(2)
        self.music.g5(2)
        self.music.modify_time(8, 1)
        self.music.a3(1)
        self.music.e4(1)
        self.music.a4(1)
        self.music.c5(1)
        self.music.e3(1)
        self.music.e4(1)
        self.music.g4(1)
        self.music.b4(1)
        # 11
        self.music.a5(4)
        self.music.g5(2)
        self.music.e5(2)
        self.music.modify_time(8, 1)
        self.music.f3(1)
        self.music.c4(1)
        self.music.f4(1)
        self.music.a4(1)
        self.music.c4(1)
        self.music.e4(1)
        self.music.g4(1)
        self.music.c5(1)
        # 12
        self.music.a5(4)
        self.music.modify_time(4, 1)
        self.music.f5(4)
        self.music.g5(2)
        self.music.modify_time(2, 1)
        self.music.d5(2)
        self.music.modify_time(8, 1)
        self.music.f3(1)
        self.music.c4(1)
        self.music.f4(1)
        self.music.a4(1)
        self.music.g3(1)
        self.music.d4(1)
        self.music.g4(1)
        self.music.b4(1)
        # 13
        self.music.c6(1)
        self.music.b5(1)
        self.music.c6(1)
        self.music.e5(1)
        self.music.g5(2)
        self.music.b5(2)
        self.music.modify_time(8, 1)
        self.music.c4(1)
        self.music.e4(1)
        self.music.g4(1)
        self.music.c5(1)
        self.music.g3(1)
        self.music.d4(1)
        self.music.g4(1)
        self.music.b4(1)
        # 14
        self.music.c6(2)
        self.music.e6(2)
        self.music.g6(1)
        self.music.e6(1)
        self.music.g6(1)
        self.music.a6(1)
        self.music.modify_time(8, 1)
        self.music.a3(1)
        self.music.e4(1)
        self.music.a4(1)
        self.music.c5(1)
        self.music.e3(1)
        self.music.e4(1)
        self.music.g4(1)
        self.music.b4(1)
        # 15
        self.music.f6(1)
        self.music.e6(1)
        self.music.d6(1)
        self.music.f6(1)
        self.music.e6(1)
        self.music.d6(1)
        self.music.c6(1)
        self.music.b5(1)
        self.music.modify_time(8, 1)
        self.music.f3(1)
        self.music.c4(1)
        self.music.f4(1)
        self.music.a4(1)
        self.music.c4(1)
        self.music.e4(1)
        self.music.g4(1)
        self.music.c5(1)
        # 16
        self.music.a5(1)
        self.music.f5(1)
        self.music.c6(2)
        self.music.b5(1)
        self.music.g5(1)
        self.music.c6(1)
        self.music.b5(1)
        self.music.modify_time(8, 1)
        self.music.f3(1)
        self.music.c4(1)
        self.music.f4(1)
        self.music.a4(1)
        self.music.g3(1)
        self.music.d4(1)
        self.music.b4(1)
        # 17
        self.music.c6(1)
        self.music.b5(1)
        self.music.c6(1)
        self.music.e5(1)
        self.music.g5(2)
        self.music.b5(2)
        self.music.modify_time(8, 1)
        self.music.c4(1)
        self.music.e4(1)
        self.music.g4(1)
        self.music.c5(1)
        self.music.g3(1)
        self.music.d4(1)
        self.music.g4(1)
        self.music.b4(1)
        # 18
        self.music.c6(2)
        self.music.e6(1)
        self.music.c6(1)
        self.music.g6(1)
        self.music.e6(1)
        self.music.g6(1)
        self.music.a6(1)
        self.music.modify_time(8, 1)
        self.music.a3(1)
        self.music.e4(1)
        self.music.a4(1)
        self.music.c5(1)
        self.music.e3(1)
        self.music.e4(1)
        self.music.g4(1)
        self.music.b4(1)
        # 19
        self.music.f6(1)
        self.music.e6(1)
        self.music.d6(1)
        self.music.f6(1)
        self.music.e6(1)
        self.music.d6(1)
        self.music.c6(1)
        self.music.b5(1)
        self.music.modify_time(8, 1)
        self.music.f3(1)
        self.music.c4(1)
        self.music.f4(1)
        self.music.a4(1)
        self.music.c4(1)
        self.music.e4(1)
        self.music.g4(1)
        self.music.c5(1)
        # 20
        self.music.a5(1)
        self.music.g5(1)
        self.music.f5(2)
        self.music.c6(1.5)
        self.music.g5(0.5)
        self.music.b5(1)
        self.music.d6(0.5)
        self.music.g5(0.5)
        self.music.modify_time(8, 1)
        self.music.f3(1)
        self.music.c4(1)
        self.music.f4(1)
        self.music.a4(1)
        self.music.g3(1)
        self.music.d4(1)
        self.music.b4(1)
        for i in range(2):
            # 21,25
            self.music.e6(1.5)
            self.music.g5(0.5)
            self.music.e6(0.5)
            self.music.d6(0.5)
            self.music.c6(0.5)
            self.music.d6(0.5)
            self.music.d6(1.5)
            self.music.e6(0.5)
            self.music.f6(0.5)
            self.music.e6(0.5)
            self.music.d6(0.5)
            self.music.e6(0.5)
            self.music.modify_time(8, 1)
            self.music.c4(1)
            self.music.e4(1)
            self.music.g4(1)
            self.music.c5(1)
            self.music.g3(1)
            self.music.d4(1)
            self.music.g4(1)
            self.music.b4(1)
            # 22,26
            self.music.c6(1.5)
            self.music.c6(0.5)
            self.music.c6(1)
            self.music.b5(0.5)
            self.music.c6(0.5)
            self.music.b5(1)
            self.music.g5(0.5)
            self.music.e5(0.5)
            self.music.e5(1)
            self.music.g5(1)
            self.music.modify_time(8, 1)
            self.music.a3(1)
            self.music.e4(1)
            self.music.a4(1)
            self.music.c5(1)
            self.music.e3(1)
            self.music.e4(1)
            self.music.g4(1)
            self.music.b4(1)
            # 23,27
            self.music.a5(2)
            self.music.b5(1)
            self.music.c6(1)
            self.music.g5(2)
            self.music.e5(1)
            self.music.g5(1)
            self.music.modify_time(8, 1)
            self.music.f3(1)
            self.music.c4(1)
            self.music.f4(1)
            self.music.a4(1)
            self.music.c4(1)
            self.music.e4(1)
            self.music.g4(1)
            self.music.c5(1)
            # 24,28
            self.music.a5(2)
            self.music.modify_time(2, 1)
            self.music.f5(2)
            self.music.f5(0.5)
            self.music.a5(0.5)
            self.music.c6(1)
            self.music.c6(1.5)
            self.music.b5(0.5)
            self.music.b5(0.5)
            self.music.c6(0.5)
            self.music.d6(0.5)
            self.music.g5(0.5)
            self.music.modify_time(8, 1)
            self.music.f3(1)
            self.music.c4(1)
            self.music.f4(1)
            self.music.a4(1)
            self.music.g3(1)
            self.music.d4(1)
            self.music.g4(1)
            self.music.b4(1)
        for i in range(2):
            # 29,33
            self.music.g6(1)
            self.music.e6(0.5)
            self.music.f6(0.5)
            self.music.g6(1)
            self.music.e6(0.5)
            self.music.f6(0.5)
            self.music.g6(0.5)
            self.music.b5(0.5)
            self.music.a5(0.5)
            self.music.b5(0.5)
            self.music.c6(0.5)
            self.music.d6(0.5)
            self.music.e6(0.5)
            self.music.f6(0.5)
            self.music.modify_time(8, 1)
            self.music.c4(1)
            self.music.g4(1)
            self.music.c5(2)
            self.music.g3(1)
            self.music.d4(1)
            self.music.b4(2)
            # 30,34
            self.music.e6(1)
            self.music.c6(0.5)
            self.music.d6(0.5)
            self.music.e6(1)
            self.music.e5(0.5)
            self.music.f5(0.5)
            self.music.g5(0.5)
            self.music.a5(0.5)
            self.music.g5(0.5)
            self.music.f5(0.5)
            self.music.g5(0.5)
            self.music.c6(0.5)
            self.music.b5(0.5)
            self.music.c6(0.5)
            self.music.modify_time(8, 1)
            self.music.a3(1)
            self.music.e4(1)
            self.music.c5(2)
            self.music.e3(1)
            self.music.e4(1)
            self.music.g4(2)
            # 31,35
            self.music.a5(1)
            self.music.c6(0.5)
            self.music.b5(0.5)
            self.music.a5(1)
            self.music.g5(0.5)
            self.music.f5(0.5)
            self.music.g5(0.5)
            self.music.f5(0.5)
            self.music.e5(0.5)
            self.music.f5(0.5)
            self.music.g5(0.5)
            self.music.a5(0.5)
            self.music.b5(0.5)
            self.music.c6(0.5)
            self.music.modify_time(8, 1)
            self.music.f3(1)
            self.music.c4(1)
            self.music.a4(2)
            self.music.c4(1)
            self.music.g4(1)
            self.music.c5(2)
            # 32,36
            self.music.a5(1)
            self.music.c6(0.5)
            self.music.b5(0.5)
            self.music.c6(1)
            self.music.b5(0.5)
            self.music.c6(0.5)
            self.music.b5(0.5)
            self.music.a5(0.5)
            self.music.b5(0.5)
            self.music.c6(0.5)
            self.music.d6(0.5)
            self.music.e6(0.5)
            self.music.f6(0.5)
            self.music.g6(0.5)
            self.music.modify_time(8, 1)
            self.music.f3(1)
            self.music.c4(1)
            self.music.a4(2)
            self.music.g3(1)
            self.music.d4(1)
            self.music.b4(2)
        # 37
        self.music.e6(1)
        self.music.c6(0.5)
        self.music.d6(0.5)
        self.music.e6(1)
        self.music.d6(0.5)
        self.music.c6(0.5)
        self.music.d6(0.5)
        self.music.b5(0.5)
        self.music.c6(0.5)
        self.music.d6(0.5)
        self.music.e6(0.5)
        self.music.d6(0.5)
        self.music.c6(0.5)
        self.music.b5(0.5)
        self.music.modify_time(8, 1)
        self.music.c4(1)
        self.music.g4(1)
        self.music.c5(2)
        self.music.g3(1)
        self.music.d4(1)
        self.music.b4(2)
        # 38
        self.music.c6(1)
        self.music.a5(0.5)
        self.music.b5(0.5)
        self.music.c6(1)
        self.music.c5(0.5)
        self.music.d5(0.5)
        self.music.e5(0.5)
        self.music.f5(0.5)
        self.music.e5(0.5)
        self.music.d5(0.5)
        self.music.e5(0.5)
        self.music.c6(0.5)
        self.music.b5(0.5)
        self.music.c6(0.5)
        self.music.modify_time(8, 1)
        self.music.a3(1)
        self.music.e4(1)
        self.music.c5(2)
        self.music.e3(1)
        self.music.e4(1)
        self.music.g4(2)
        # 39
        self.music.a5(1)
        self.music.c6(0.5)
        self.music.b5(0.5)
        self.music.a5(1)
        self.music.g5(0.5)
        self.music.f5(0.5)
        self.music.g5(0.5)
        self.music.f5(0.5)
        self.music.e5(0.5)
        self.music.f5(0.5)
        self.music.g5(0.5)
        self.music.a5(0.5)
        self.music.b5(0.5)
        self.music.c6(0.5)
        self.music.modify_time(8, 1)
        self.music.f3(1)
        self.music.c4(1)
        self.music.a4(2)
        self.music.c4(1)
        self.music.g4(1)
        self.music.c5(2)
        # 40
        self.music.a5(1)
        self.music.c6(0.5)
        self.music.b5(0.5)
        self.music.c6(1)
        self.music.b5(0.5)
        self.music.a5(0.5)  # #
        self.music.b5(0.5)
        self.music.c6(0.5)
        self.music.d6(0.5)
        self.music.c6(0.5)
        self.music.b5(0.5)
        self.music.c6(0.5)
        self.music.a5(0.5)
        self.music.b5(0.5)
        self.music.modify_time(8, 1)
        self.music.f3(1)
        self.music.c4(1)
        self.music.a4(2)
        self.music.g3(1)
        self.music.d4(1)
        self.music.b4(2)
        # 41
        self.music.c6(8)
        self.music.modify_time(8, 1)
        self.music.c4(1)
        self.music.g4(1)
        self.music.c5(1)
        self.music.e5(1)
        self.music.g3(1)
        self.music.d4(1)
        self.music.g4(1)
        self.music.b4(1)
        # 42
        self.music.modify_time(8, 0)
        self.music.modify_time(8, 1)
        self.music.a3(1)
        self.music.e4(1)
        self.music.a4(1)
        self.music.c5(1)
        self.music.e3(1)
        self.music.e4(1)
        self.music.g4(1)
        self.music.b4(1)
        # 43
        self.music.modify_time(8, 0)
        self.music.modify_time(8, 1)
        self.music.f3(1)
        self.music.c4(1)
        self.music.f4(1)
        self.music.a4(1)
        self.music.c4(1)
        self.music.g4(1)
        self.music.c5(1)
        self.music.e5(1)
        # 44
        self.music.modify_time(8, 0)
        self.music.modify_time(8, 1)
        self.music.f3(1)
        self.music.c4(1)
        self.music.f4(1)
        self.music.a4(1)
        self.music.g3(1)
        self.music.d4(1)
        self.music.g4(1)
        self.music.b4(1)





        with open(self.name, "wb") as output_file:
            self.music.get_midi().writeFile(output_file)
        return self.name
